default_language_version:
  python: python3

repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: name-tests-test
        args: [ --django ]
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [ --autofix ]
      - id: fix-encoding-pragma
        args: [ --remove ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [
            'flake8-bugbear',
            'flake8-commas',
            'flake8-rst-docstrings',
            'flake8-string-format',
            'flake8-docstrings',
            'flake8-quotes',
            'flake8-bandit',
            'flake8-debugger',
            'flake8-broken-line',
        ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.6.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: python
        entry: pytest
        pass_filenames: false
        always_run: true
