repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-case-conflict
      - id: check-toml
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: fix-encoding-pragma
      - id: name-tests-test
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: pretty-format-json
          args: [ --autofix ]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: [ --line-length=150,
                --safe,
                --skip-string-normalization
        ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [
            '--max-line-length=150',
            '--ignore=E203,E402,E501,E800,W503,W391,E261',
            '--select=B,C,E,F,W,T4,B9'
        ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: [ --line-length=150 ]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest
        pass_filenames: false
        always_run: true
